name: cd

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            exe: gmod_lzma.exe
            release_exe: gmod_lzma_win64.exe

          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            exe: gmod_lzma
            release_exe: gmod_lzma_linux64

          - target: x86_64-apple-darwin
            os: macos-13
            exe: gmod_lzma
            release_exe: gmod_lzma_macos_x86-64

          - target: aarch64-apple-darwin
            os: macos-latest
            exe: gmod_lzma
            release_exe: gmod_lzma_macos_arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build --package gmod-lzma-cli --release --target ${{ matrix.target }}
          mv target/${{ matrix.target }}/release/${{ matrix.exe }} target/release/${{ matrix.release_exe }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/${{ matrix.release_exe }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
